name: Build, Deploy, and Push

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      ECR_REPOSITORY: faq-bot-practice # UPDATE THIS with your repo name
      AWS_REGION: ap-southeast-1 # UPDATE THIS with your AWS region

    # These permissions are needed for the aws-actions/configure-aws-credentials action
    # to use OIDC for authentication, which is more secure than long-lived access keys.
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Define image URI and build Docker image
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        # Define the full image URI and make it available to subsequent steps
        IMAGE_URI="$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
        echo "image_uri=$IMAGE_URI" >> $GITHUB_ENV

        # Build the docker image
        docker build -t $IMAGE_URI .

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      id: plan
      run: terraform plan -var="ecr_image_identifier=${{ env.image_uri }}"

    - name: Terraform Apply
      run: terraform apply -auto-approve -var="ecr_image_identifier=${{ env.image_uri }}"

    - name: Push image to Amazon ECR
      run: docker push ${{ env.image_uri }}
