# Name of the workflow
name: Docker Build CI

# 1. Trigger: This workflow runs on any push to the "main" branch.
on:
  push:
    branches: [ "main" ]

# A workflow is made of one or more jobs.
jobs:
  # We have one job named "build".
  build:
    # 2. Environment: The job will run on a fresh virtual machine running Ubuntu.
    runs-on: ubuntu-latest
    # permissions:
    #   contents: read
    #   packages: write

    # 3. Steps: A sequence of tasks to execute.
    steps:
    # First, check out the repository's code so the workflow can access it.
    - name: Checkout repository
      uses: actions/checkout@v4

    # Second, run the standard docker build command.
    - name: Build Docker image
      run: docker build . --file Dockerfile --tag my-faq-bot:latest

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build, tag, and push Docker image
      run: |
        IMAGE_ID=ghcr.io/${{ github.repository }}:${{ github.sha }}
        docker build . --tag $IMAGE_ID
        docker push $IMAGE_ID
  # deploy:
  #   # This job will only start if the 'build' job finishes successfully.
  #   needs: build
  #   runs-on: ubuntu-latest

  #   steps:
  #   # Step 1: Log in to the cloud provider (Azure).
  #   # Credentials are saved as encrypted secrets in GitHub.
  #   - name: 'Log in to Azure'
  #     uses: azure/login@v1
  #     with:
  #       creds: ${{ secrets.AZURE_CREDENTIALS }}

  #   # Step 2: Use a specialized action to deploy our image.
  #   # We tell it which image to deploy from our registry.
  #   - name: 'Deploy to Azure Container Apps'
  #     uses: azure/container-apps-deploy-action@v1
  #     with:
  #       imageToDeploy: ghcr.io/${{ github.repository }}:${{ github.sha }}
