name: Build, Deploy, and Push

on:
  push:
    branches: [ "main" ]

env:
  ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY_NAME || 'faq-bot-practice' }}
  AWS_REGION: ${{ vars.AWS_REGION || 'ap-southeast-1' }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    # These permissions are needed for the aws-actions/configure-aws-credentials action
    # to use OIDC for authentication, which is more secure than long-lived access keys.
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Define image URI and build Docker image
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        # Build the Docker image
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .

        # Push the Docker image to ECR
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

        # Set the full image URI as an output of THIS specific step
        echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      id: plan
      run: terraform plan -var="ecr_image_identifier=${{ steps.build-image.outputs.image }}"

    - name: Terraform Apply
      run: terraform apply -auto-approve -var="ecr_image_identifier=${{ steps.build-image.outputs.image }}"
